name: youtube_iframe_interop
description: Youtube Iframe API interop
version: 0.2.0
homepage: https://github.com/leftyio/youtube_iframe_interop
authors:
  - Kevin Segaud <segaud.kevin@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_browser_loader: ^0.1.0
  js: ^0.6.3

dev_dependencies:
  build: ^2.0.0
  build_runner: ^1.10.0
  build_test: ^2.0.0
  build_web_compilers: ^2.15.0
  pedantic: ^1.10.0
