name: youtube_iframe_interop
description: Youtube Iframe API interop
version: 1.0.0
homepage: https://github.com/leftyio/youtube_iframe_interop

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_browser_loader: ^1.0.0
  js: ^0.6.3

dev_dependencies:
  build: ^2.0.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
