name: youtube_iframe_interop
description: Youtube Iframe API interop
version: 0.1.0
homepage: https://lefty.io/
authors: 
  - Kevin Segaud <segaud.kevin@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  dart_browser_loader: ^0.0.5
  js: '>=0.6.1 <0.7.0'

dev_dependencies:
  build: ^1.0.0
  build_runner: ^1.0.0
  build_test: '>=0.10.0 <1.0.0'
  build_web_compilers: '>=0.4.0 <1.0.0'